[workspace]
members = ["ktann-foundationdb", "ktann-rocksdb"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/Lloyd-Pottiger/ktann"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"

[package]
name = "ktann"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "K-means Tree Approximate Nearest Neighbor library"

[lib]
path = "src/lib.rs"

[features]
default = []

[lints]
workspace = true
